### ISSUE TITLE
Add patch to find the right libGL

### ISSUE THREAD

**Issue by dc740** [chessgriffin/obsd-minecraft#1]
1) in src/native/linux/openGL/extgl_glx.c:
line 222:
# ifdef  __OpenBSD__

```
lib_gl_handle = dlopen("libGL.so.15.0", RTLD_LAZY | RTLD_GLOBAL);
```
# else

```
lib_gl_handle = dlopen("libGL.so.1", RTLD_LAZY | RTLD_GLOBAL);
```
# endif

You don't need the symbolic link anymore after that patch!

2) Also, please add a comment here:
https://github.com/LWJGL/lwjgl/pull/54

3) I tried to contact you but I couldn't find any email in your profile. This is the only way I found.

4) The hardware render is extremely slow on my machine compared to the soft renderer

5) I was too lazy to submit a patch. I know.

**Comment by chessgriffin** [comment]
Thanks for this. :-)

I'll try this and come up with a patch as soon as I can and then update the writeup.

That's strange that the hardware renderer is slower on your system compared to the software one.  It's the opposite for me -- I've got minecraft running on my 5.6-current laptop with intel 4000 graphics and the hardware renderer works fine.

Cheers!

**Comment by qbit** [comment]
@dc740 are you using Intel or an ATI card (something with KMS support)?

**Comment by chessgriffin** [comment]
Yes, Intel HD 4000 with KMS support on Thinkpad X230 laptop.

Scratch that - sorry qbit, I thought you were directing that to me.

**Comment by qbit** [comment]
@chessgriffin no worries - Knowing both is good! I would have been impressed if you had quick 3d rendering on non-KMS hardware!

**Comment by chessgriffin** [comment]
True enough.  :-)  I haven't tried your patches yet but I will and I will also point people to them in my writeup.

**Comment by dc740** [comment]
I'm using an ATI Radeon HD 7770. 1GB of RAM.
CPU AMD 6100 x6 (I can't recall the exact Ghz, something between 3,1 and 4Ghz. I think 4 in turbo mode)
8GB ddr3 ram
and again, I can't recall my motherboard. It's been a really long time since I built this PC.

**Comment by chessgriffin** [comment]
Not sure if this thread on misc@ is relevant but it might be that OpenBSD does not yet support that card:

http://marc.info/?t=140338300100006&r=1&w=2

**Comment by dc740** [comment]
You are right. That's the problem. Looks like I'll be using the software rendered for a long time. Thanks guys

**Comment by qbit** [comment]
Just sent in a port to ports@ with info to here, and the diffs required for version 2.9.1 (mine are all for upstream lwjgl) :dancer: 

Thanks @dc740 and @chessgriffin !

**Comment by dc740** [comment]
you are welcome. thank you guys for the original ant changes. I can confirm that the low performance was caused by the lack of acceleration in the new GCN architecture cards. I switched to the onboard card and it's working perfectly now!
 1:5:0: ATI Radeon HD 3000  <--- works great
 2:0:0: ATI Radeon HD 7770 <--- GCN architecture. doesn't have acceleration in OpenBSD 5.5

**Comment by chessgriffin** [comment]
NICE! Thanks for doing that, @qbit!  That is totally awesome.   Hopefully it'll be accepted and then I can remove 9 out of the 10 steps from this writeup.  :-)

**Comment by jarmani** [comment]
Hi,

I think you want let ld to determine the version of the library to load

```
#ifdef __OpenBSD__
lib_gl_handle = dlopen("libGL.so", RTLD_LAZY | RTLD_GLOBAL);
#else
lib_gl_handle = dlopen("libGL.so.1", RTLD_LAZY | RTLD_GLOBAL);
#endif
```

**Comment by dc740** [comment]
Thanks Jonathan, I actually didn't know you could simply do that. in that case:
lib_gl_handle = dlopen("libGL.so", RTLD_LAZY | RTLD_GLOBAL);

that would be more than enough for any system

**Comment by jarmani** [comment]
Yeah I had my patches when I ported it some time ago

FWIW I commited them just in case https://github.com/jarmani/lwjgl/compare/openbsd

**Comment by chessgriffin** [comment]
Cool stuff, thanks guys.

**Comment by dc740** [comment]
Guys, I finally created the last patch. If this pull request gets accepted, then OpenBSD gets  complete support in the official lwjgl repository. Thank you all!

https://github.com/LWJGL/lwjgl/pull/92

**Comment by chessgriffin** [comment]
Nice, thanks @dc740!

**Comment by qbit** [comment]
I just imported lwjgl :D

**Comment by chessgriffin** [comment]
@qbit \o/

Thanks to you and @dc740 to get everything done.  It looks like @dc740's last patch was just accepted by upsteam today so hopefully that would mean you could drop the patches from the port @qbit is that correct?  BTW, I did test your port last night and worked great.  I made a minor tweak to the minecraft helper script and everything worked fine.  Thanks to both of you!

**Comment by qbit** [comment]
@chessgriffin correct, likely the next version of LWJGL will include those fixes and all the patches in the port can be removed!

**Comment by dc740** [comment]
I still ahve a doubt. @jarmani: you mentioned you ported it to OpenBSD before. 1) Did you make the port public? 2)did you try to setup a port before qbit?

**Comment by chessgriffin** [comment]
I've been working at updating the README writeup for the time being but eventually most of it will not be needed b/c of @qbit's port. :-)  Thank you @dc740 for starting this discussion and pointing out the right way to fix my dumb symbolic link hack and thank you @qbit for pulling everything together to make a port.  Cheers to you both!
